data_miner:
  api_base: "https://openrouter.ai/api/v1"
  api_key: ""
  model: "deepseek/deepseek-chat"
  temperature: 0.7
  max_tokens: 1000
  chunk_size: 1000
  chunk_overlap: 200
  system_prompt: |
    Ты AI-агент Data Miner, специализирующийся на анализе PDF-документов.
    Извелечи информацию в формате JSON: Название организации, Телефон, Электронная почта, БИК, ОГРН.
    Если информации нет, то отправь пустой JSON.